// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-JYOakQBzGvadMpr8ji3zE_AhvZ3bq7k',
    appId: '1:478862318784:web:00861c77ffc6b5c6b0a125',
    messagingSenderId: '478862318784',
    projectId: 'newagent-ki9i',
    authDomain: 'newagent-ki9i.firebaseapp.com',
    storageBucket: 'newagent-ki9i.appspot.com',
    measurementId: 'G-FJYPX4063Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAnLhKiI37Gck5cubrQIDENCUA3Jty98',
    appId: '1:478862318784:android:21508da8f93c8fdfb0a125',
    messagingSenderId: '478862318784',
    projectId: 'newagent-ki9i',
    storageBucket: 'newagent-ki9i.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJwZSklyJ2eeZ2WGba4h3w2xMXBiD6Y9I',
    appId: '1:478862318784:ios:9cec0ec33faf5af8b0a125',
    messagingSenderId: '478862318784',
    projectId: 'newagent-ki9i',
    storageBucket: 'newagent-ki9i.appspot.com',
    androidClientId: '478862318784-dn9l6msj8pgrvpodgfcmijbcdr3mm656.apps.googleusercontent.com',
    iosClientId: '478862318784-hj8ke77gc7bji9nfvk63vk53mqkvf55d.apps.googleusercontent.com',
    iosBundleId: 'com.anhnguyen.glance',
  );
}
